[2025-04-01T18:48:08.386+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T18:48:08.395+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task2 manual__2025-04-01T18:48:06.651199+00:00 [queued]>
[2025-04-01T18:48:08.399+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task2 manual__2025-04-01T18:48:06.651199+00:00 [queued]>
[2025-04-01T18:48:08.399+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-04-01T18:48:08.404+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task2> on 2025-04-01 18:48:06.651199+00:00
[2025-04-01T18:48:08.410+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task2', 'manual__2025-04-01T18:48:06.651199+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp_s3y34d6']
[2025-04-01T18:48:08.411+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5245) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-01T18:48:08.411+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask task2
[2025-04-01T18:48:08.411+0000] {standard_task_runner.py:72} INFO - Started process 5246 to run task
[2025-04-01T18:48:08.437+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.task2 manual__2025-04-01T18:48:06.651199+00:00 [running]> on host 7d980c7fabe2
[2025-04-01T18:48:08.488+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='grypton' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T18:48:06.651199+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T18:48:06.651199+00:00'
[2025-04-01T18:48:08.489+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-01T18:48:08.509+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-01T18:48:08.511+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'I am second task, and I will be running after task1'"]
[2025-04-01T18:48:08.517+0000] {subprocess.py:99} INFO - Output:
[2025-04-01T18:48:08.523+0000] {subprocess.py:106} INFO - I am second task, and I will be running after task1
[2025-04-01T18:48:08.524+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-01T18:48:08.581+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-01T18:48:08.583+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task2, run_id=manual__2025-04-01T18:48:06.651199+00:00, execution_date=20250401T184806, start_date=20250401T184808, end_date=20250401T184808
[2025-04-01T18:48:08.667+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-01T18:48:08.684+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-01T18:48:08.685+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
