[2025-04-01T19:14:13.425+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T19:14:14.195+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task3 manual__2025-04-01T19:14:05.034732+00:00 [queued]>
[2025-04-01T19:14:17.255+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task3 manual__2025-04-01T19:14:05.034732+00:00 [queued]>
[2025-04-01T19:14:17.272+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-04-01T19:14:17.345+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task3> on 2025-04-01 19:14:05.034732+00:00
[2025-04-01T19:14:17.395+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5835) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-01T19:14:17.382+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task3', 'manual__2025-04-01T19:14:05.034732+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpbhq4w1qw']
[2025-04-01T19:14:17.399+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask task3
[2025-04-01T19:14:17.403+0000] {standard_task_runner.py:72} INFO - Started process 5838 to run task
[2025-04-01T19:14:23.797+0000] {job.py:229} INFO - Heartbeat recovered after 11.44 seconds
[2025-04-01T19:14:24.015+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.task3 manual__2025-04-01T19:14:05.034732+00:00 [running]> on host 7d980c7fabe2
[2025-04-01T19:14:24.629+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='grypton' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task3' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T19:14:05.034732+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T19:14:05.034732+00:00'
[2025-04-01T19:14:24.638+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-01T19:14:24.675+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-01T19:14:24.682+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'I am third task'"]
[2025-04-01T19:14:24.693+0000] {subprocess.py:99} INFO - Output:
[2025-04-01T19:14:24.716+0000] {subprocess.py:106} INFO - I am third task
[2025-04-01T19:14:24.719+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-01T19:14:24.791+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-01T19:14:24.794+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task3, run_id=manual__2025-04-01T19:14:05.034732+00:00, execution_date=20250401T191405, start_date=20250401T191414, end_date=20250401T191424
[2025-04-01T19:14:24.902+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-01T19:14:24.926+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-01T19:14:24.928+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
