[2025-04-01T19:14:13.326+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T19:14:14.007+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task2 manual__2025-04-01T19:14:05.034732+00:00 [queued]>
[2025-04-01T19:14:14.215+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task2 manual__2025-04-01T19:14:05.034732+00:00 [queued]>
[2025-04-01T19:14:14.235+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-04-01T19:14:17.278+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task2> on 2025-04-01 19:14:05.034732+00:00
[2025-04-01T19:14:17.305+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task2', 'manual__2025-04-01T19:14:05.034732+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmphxezue59']
[2025-04-01T19:14:17.334+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask task2
[2025-04-01T19:14:17.330+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5834) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-01T19:14:17.335+0000] {standard_task_runner.py:72} INFO - Started process 5836 to run task
[2025-04-01T19:14:22.901+0000] {job.py:229} INFO - Heartbeat recovered after 10.63 seconds
[2025-04-01T19:14:23.947+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.task2 manual__2025-04-01T19:14:05.034732+00:00 [running]> on host 7d980c7fabe2
[2025-04-01T19:14:24.629+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='grypton' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T19:14:05.034732+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T19:14:05.034732+00:00'
[2025-04-01T19:14:24.635+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-01T19:14:24.676+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-01T19:14:24.682+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'I am second task'"]
[2025-04-01T19:14:24.697+0000] {subprocess.py:99} INFO - Output:
[2025-04-01T19:14:24.716+0000] {subprocess.py:106} INFO - I am second task
[2025-04-01T19:14:24.719+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-01T19:14:24.791+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-01T19:14:24.794+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task2, run_id=manual__2025-04-01T19:14:05.034732+00:00, execution_date=20250401T191405, start_date=20250401T191414, end_date=20250401T191424
[2025-04-01T19:14:24.911+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-01T19:14:24.921+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
